#.travis.yml
language: node_js
node_js:
  - "13"
branches:
  only:
    - master
    - develop
script:
  - echo "Deploy Firebase"
install:
  - npm install -g firebase-tools
after_success:
  - cd functions
  - npm install
  - npm run deploy
